import json
import logging
from typing import Dict, Any
from app.services.gemini import gemini_service

logger = logging.getLogger("aarogya.ocr")

class OCRService:
    def ocr_prescription(self, image_bytes: bytes, mime_type: str = "image/jpeg") -> Dict[str, Any]:
        """
        Process a handwritten or printed prescription image, extracting structured medicine parameters.
        """
        prompt = """
        You are a highly precise medical AI and clinical pharmacy expert. 
        Read this handwritten or printed prescription, determine the diagnosis/medical condition, and extract all listed medications.
        Return your analysis STRICTLY in JSON format matching the schema below.
        Do not add any markup, comments, or explanations outside the JSON block.

        Expected JSON format:
        {
          "issue_date": "YYYY-MM-DD", // Date of prescription if visible, otherwise null
          "diagnosis": "Primary diagnosis/medical condition if visible, otherwise null",
          "medicines": [
            {
              "name": "Exact Name of Medicine",
              "dosage": "Dosage format, e.g. '400mg', '500mg', '1 tablet'",
              "frequency": "Frequency, e.g. 'once daily', 'twice daily', 'BD', 'TDS', 'OD'",
              "duration": "Duration format, e.g. '5 days', '10 days', '30 days'",
              "schedule_time": "HH:MM:SS format representing standard timing (morning: '08:00:00', afternoon: '13:00:00', night: '20:00:00', weekly: '08:00:00')",
              "duration_days": 30 // Number of days to take, default to 30 if not specified
            }
          ]
        }
        Ensure dosage, frequency, and time schedules are carefully aligned. If multiple times are written (e.g. morning and night), create separate entries for each scheduled time.
        """
        try:
            response_text = gemini_service.generate_content(
                prompt=prompt,
                image_bytes=image_bytes,
                image_mime=mime_type
            )
            # Remove any markdown code block wrappers if generated by LLM fallback
            clean_json = response_text.replace("```json", "").replace("```", "").strip()
            return json.loads(clean_json)
        except Exception as e:
            logger.error(f"Prescription OCR extraction failed: {str(e)}")
            # Return empty skeleton on error
            return {"issue_date": None, "diagnosis": None, "medicines": []}

    def ocr_lab_report(self, image_bytes: bytes, mime_type: str = "image/jpeg") -> Dict[str, Any]:
        """
        Process a blood or diagnostic lab report image, extracting medical metrics, reference values, and alert states.
        """
        prompt = """
        You are a clinical diagnostic expert.
        Analyze this blood test/lab report image and extract all biochemical metrics, values, and normal ranges.
        Return your analysis STRICTLY in JSON format matching the schema below.
        Do not add any markup, comments, or explanations outside the JSON block.

        Expected JSON format:
        {
          "report_type": "Blood Test", // e.g. "Complete Blood Count", "Lipid Profile", "Diabetic Panel"
          "metrics": {
            "HbA1c": {
              "value": 8.1,
              "unit": "%",
              "reference_range": "4.0 - 5.6",
              "status": "high" // "normal" | "low" | "high"
            },
            "Fasting Blood Sugar": {
              "value": 152.0,
              "unit": "mg/dL",
              "reference_range": "70 - 100",
              "status": "high"
            }
          },
          "summary": "Clinical summary of findings in clear medical terms"
        }
        """
        try:
            response_text = gemini_service.generate_content(
                prompt=prompt,
                image_bytes=image_bytes,
                image_mime=mime_type
            )
            clean_json = response_text.replace("```json", "").replace("```", "").strip()
            return json.loads(clean_json)
        except Exception as e:
            logger.error(f"Lab Report OCR extraction failed: {str(e)}")
            return {"report_type": "Unknown", "metrics": {}, "summary": "Failed to parse report."}

ocr_service = OCRService()
